security:
    password_hashers:
        App\Entity\User: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            logout:
                path: logout               # Route for logging out
                target: /                 # Redirect after logout

    access_control:
        # Admin pages only accessible by ROLE_ADMIN
        - { path: ^/admin, roles: ROLE_ADMIN }
        # User pages accessible by ROLE_USER
        - { path: ^/user, roles: ROLE_USER }
